# @package agent
_target_: agent.rune_sac.RuneSACAgent
name: rune_sac
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: 1024
feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
# sf_dim: 10
# update_task_every_step: 5
nstep: 3
batch_size: 1024
init_critic: true
init_all: false
knn_rms: false  # original true, pebble is false
knn_k: 5  # original 12, pebble is 5
knn_avg: false  # original true, pebble is false
knn_clip: 0  # original 0.0001, pebble is 0
num_init_steps: 4096 # set to ${num_train_frames} to disable finetune policy parameters
# lstsq_batch_size: 4096
update_encoder: ${update_encoder}

# for sac
alpha: 0.2
autotune_alpha: true