# @package agent
name: sac_dev_metaworld
_target_: agent.sac_dev.SACAgent
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
num_expl_steps: ??? # to be specified later
discount: 0.99
init_temperature: 0.1
alpha_lr: 1e-4
alpha_betas: [0.9, 0.999]
actor_lr: 1e-4
actor_betas: [0.9, 0.999]
actor_update_frequency: 1
critic_lr: 1e-4
critic_betas: [0.9, 0.999]
critic_tau: 0.005
critic_target_update_frequency: 2
batch_size: 512 # 1024 for Walker, 512 for Meta-world
learnable_temperature: true
init_all: false

# temporarily unused
update_every_steps: 2
use_tb: ${use_tb}
use_wandb: ${use_wandb}
reward_free: ${reward_free}
  
critic_cfg:
  class: agent.utils.critic.DoubleQCritic
  # obs_dim: ??? # to be specified later
  # action_dim: ??? # to be specified later
  hidden_dim: 256
  hidden_depth: 3
    
actor_cfg:
  class: agent.utils.actor.DiagGaussianActor
  # obs_dim: ??? # to be specified later
  # action_dim: ??? # to be specified later
  hidden_depth: 3
  hidden_dim: 256
  log_std_bounds: [-5, 2]
